# Generated by Django 3.0.4 on 2020-03-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_num', models.IntegerField(help_text='Enterthe number of this publication.', verbose_name='Publication Number')),
                ('author', models.CharField(help_text='Enterthe author(s) who wrote this publication.', max_length=10000, verbose_name='Author(s)')),
                ('year', models.IntegerField(help_text='Enter the year the publication was published.')),
                ('letter', models.CharField(help_text='Enter a letter to follow thepublication year, if this publication shares theexact same authors and author order as another publication.', max_length=2)),
                ('journal_title', models.CharField(help_text='Enter the title ofthe publication.', max_length=1000)),
                ('journal', models.CharField(help_text='Enter the journal where thepublication was published.', max_length=1000)),
                ('volume_num', models.IntegerField(blank=True, help_text='Enter the volume number, if the publication has one.', null=True, verbose_name='Volume Number')),
                ('issue_num', models.IntegerField(blank=True, help_text='Enter the issue number, if the publication has one.', null=True, verbose_name='IssueNumber')),
                ('pages', models.CharField(blank=True, help_text='Enter the pagesfor the publication.', max_length=20, null=True)),
                ('editor', models.CharField(blank=True, help_text='Enter thename(s) of the editor(s), if this publication has editor(s).', max_length=1000, null=True)),
                ('chapter_title', models.CharField(blank=True, help_text='Enterthe chapter title of the publication.', max_length=1000, null=True)),
                ('book_title', models.CharField(blank=True, help_text='Enter thebook title of the publication.', max_length=1000, null=True)),
                ('edition', models.IntegerField(blank=True, help_text='Enter the edition of the publication.', null=True)),
                ('volume', models.IntegerField(blank=True, help_text='Enter the volume number.', null=True)),
                ('publisher', models.CharField(blank=True, help_text='Enter thename of the publisher, if the publication is a book.', max_length=1000, null=True)),
                ('publisher_country', models.CharField(blank=True, help_text='Enterthe country of the publisher.', max_length=100, null=True)),
                ('book_pages', models.CharField(blank=True, help_text="Enter thebook's pages.", max_length=10, null=True)),
                ('pdf', models.FileField(upload_to='publication-pdfs')),
            ],
            options={
                'ordering': ['pub_num', 'author', 'year'],
            },
        ),
    ]
