# Generated by Django 3.0.4 on 2020-03-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.CharField(blank=True, help_text='Enter the author(s) who wrote this publication.', max_length=10000, null=True, verbose_name='Author(s)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='book_pages',
            field=models.CharField(blank=True, help_text="Enter the book's pages.", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='book_title',
            field=models.CharField(blank=True, help_text='Enter the book title of the publication.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='chapter_title',
            field=models.CharField(blank=True, help_text='Enter the chapter title of the publication.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='editor',
            field=models.CharField(blank=True, help_text='Enter the name(s) of the editor(s), if this publication has editor(s).', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal',
            field=models.CharField(blank=True, help_text='Enter the journal where the publication was published.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal_title',
            field=models.CharField(blank=True, help_text='Enter the title of the publication.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='letter',
            field=models.CharField(blank=True, help_text='Enter a letter to follow the publication year, if this publication shares the exact same authors and author order as another publication.', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pages',
            field=models.CharField(blank=True, help_text='Enter the pages for the publication.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='publication-pdfs'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pub_num',
            field=models.IntegerField(blank=True, help_text='Enter the number of this publication.', null=True, verbose_name='Publication Number'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publisher',
            field=models.CharField(blank=True, help_text='Enter the name of the publisher, if the publication is a book.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publisher_country',
            field=models.CharField(blank=True, help_text='Enter the country of the publisher.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.IntegerField(blank=True, help_text='Enter the year the publication was published.', null=True),
        ),
    ]
