# Generated by Django 3.0.4 on 2020-03-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200320_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='journal_title',
            field=models.CharField(blank=True, help_text='Enter the title of the publication. If the title has scientific names, put the scientific name between "<\\i>" and "<\\/i>" tags. This will render the name in italics on the website.', max_length=1000, null=True),
        ),
    ]
