# Generated by Django 3.0.4 on 2020-03-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='day',
            field=models.CharField(blank=True, help_text='Enter the day(s) the presentation was presented.', max_length=5, null=True, verbose_name='day(s)'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='location',
            field=models.CharField(blank=True, help_text='Enter the location where the presentation was presented.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='meeting',
            field=models.CharField(blank=True, help_text='Enter the meeting at which the presentation was presented.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='month',
            field=models.CharField(blank=True, help_text='Enter the month the presentation was presented.', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='presenter',
            field=models.CharField(blank=True, help_text='Enter the name of the presenter.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='symposium',
            field=models.CharField(blank=True, help_text='Enter the symposium for this presentation, if it was presented in one.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='title',
            field=models.CharField(blank=True, help_text='Enter the title of the presenation. If the title has scientific names, put the scientific name between "&lt;i&gt;" and "&lt;/i&gt;" tags. This will render the name in italics on the website.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='year',
            field=models.IntegerField(blank=True, help_text='Enter the year the presentation was presented.', null=True),
        ),
    ]
