# Generated by Django 3.0.4 on 2020-03-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20200329_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='status',
            field=models.CharField(blank=True, help_text='Select the status of the publication.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='month',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], help_text='Select the month the presentation was presented.', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pub_num',
            field=models.IntegerField(blank=True, help_text='Enter the number of this publication, if it is published.', null=True, verbose_name='Publication Number'),
        ),
    ]
