# Generated by Django 3.0.4 on 2020-03-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20200329_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(blank=True, choices=[('Published', 'Published'), ('Accepted', 'Accepted'), ('Submitted', 'Submitted'), ('In prep', 'In prep')], help_text='Select the status of the publication.', max_length=20, null=True),
        ),
    ]
