# Generated by Django 3.0.4 on 2020-04-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_auto_20200402_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='location',
            field=models.TextField(blank=True, help_text='Enter the location where the presentation was presented, as well as any details regarding the meeting.', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='presenter',
            field=models.CharField(blank=True, help_text='Enter the name of the presenter if it was someone other than yourself.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='title',
            field=models.TextField(blank=True, help_text='Enter the title of the presenation. If the title has scientific names, put the scientific name between "&lt;i&gt;" and "&lt;/i&gt;" tags. This will render the name in italics on the website.', max_length=1000, null=True),
        ),
    ]
