# Generated by Django 3.0.4 on 2020-04-02 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_auto_20200402_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.IntegerField(blank=True, help_text='Enter the year of publication', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
