# Generated by Django 3.0.4 on 2020-04-02 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_auto_20200402_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='year',
            field=models.IntegerField(blank=True, help_text='Enter the year the presentation was presented.', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='travel',
            name='year',
            field=models.IntegerField(blank=True, help_text='Enter the year of travel.', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
