# Generated by Django 3.0.4 on 2020-04-02 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_auto_20200402_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, help_text='Enter the year of the fellowship or grant.', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('amount', models.IntegerField(blank=True, help_text='Enter the amount of the fellowship or grant.', null=True)),
                ('grant_details', models.TextField(blank=True, help_text='Enter the details of the fellowship or grant.', max_length=10000, null=True, verbose_name='Fellowship or grant details')),
            ],
            options={
                'ordering': ['year', 'amount', 'grant_details'],
            },
        ),
    ]
