# Generated by Django 3.0.4 on 2020-04-02 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_society'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='society',
            options={'verbose_name': 'Societies'},
        ),
    ]
