# Generated by Django 3.0.4 on 2020-04-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_auto_20200402_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='society',
            options={'verbose_name_plural': 'Societies'},
        ),
    ]
