# Generated by Django 3.0.4 on 2020-04-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_auto_20200402_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='society',
            options={'ordering': ['society'], 'verbose_name_plural': 'Societies'},
        ),
    ]
