# Generated by Django 3.0.4 on 2020-05-10 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_auto_20200402_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='pub_num',
            field=models.IntegerField(blank=True, default='1', help_text="Enter the publication's number.", null=True, verbose_name='Publication Number'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='presenter',
            field=models.CharField(blank=True, help_text='Enter the name of the presenter if it was someone other than yourself. Leave blank if you presented.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.IntegerField(blank=True, help_text='Enter the year of publication.', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
